// Lecture_10/vue-app/src/components/addItem.vue
<template>
  <li class="list-group-item">
    <div class="input-group col-md-8">
    <input class="form-control"  type="text" v-model="inputValue"/>
      <span class="input-group-btn">
    <button class="btn btn-default" v-on:click="addNewItem"> Add item </button>
      </span>
    </div>
  </li>

</template>

<script>
let inputValue = ''

export default {
  name: 'addItem',
  data: function () {
    return {
      inputValue
    }
  },
  methods: {
    addNewItem: function () {
      this.$emit('onAddNewItem', this.inputValue)
      this.inputValue = ''
    }
  }
}

</script>

// Lecture_10/angular-app/src/app/list/addItem.component/addItem.component.ts
import {Component, EventEmitter, Output} from '@angular/core';

@Component({
  selector: 'app-add-item',
  templateUrl: './addItem.component.html',
  styleUrls: []
})

export class AddItemComponent {
  @Output() onAddItem: EventEmitter<string> = new EventEmitter<string>();

  inputValue = '';

  addNewItem() {
    this.onAddItem.emit(this.inputValue);
    this.inputValue = '';
  }

}

<li class="list-group-item">
<div class="input-group col-md-8">
  <input class="form-control" type="text" [(ngModel)]="inputValue"/>
  <span class="input-group-btn">
    <button class="btn btn-default" (click)="addNewItem()"> Add item </button>
  </span>
</div>
</li>
