// Lecture_10/angular-app/src/app/list/activeItem.component/activeItem.component.ts
import {Component, EventEmitter, Input, OnChanges, Output, SimpleChanges} from '@angular/core';
import {ListItem} from '../../../models/ListItem';

@Component({
  selector: 'app-active-item',
  templateUrl: './activeItem.component.html',
  styleUrls: []
})

export class ActiveItemComponent implements OnChanges {
  @Input() index: number;
  @Input() item: ListItem;
  @Output() onSaveItem: EventEmitter<string> = new EventEmitter<string>();
  @Output() onCancelEditing: EventEmitter<never> = new EventEmitter<never>();
  @Output() onDeleteItem: EventEmitter<never> = new EventEmitter<never>();
  inputValue: string;


  ngOnChanges(changes: SimpleChanges): void {
    this.inputValue = this.item.text;
  }

  saveItem = () => this.onSaveItem.emit(this.inputValue);


  cancelEditing = () => this.onCancelEditing.emit();


  deleteItem = () => this.onDeleteItem.emit();

}

<div class="input-group col-md-8">
  <span class="input-group-addon">
       {{index + 1}}.
   </span>
  <input class="form-control" type="text" [(ngModel)]="inputValue"/>
  <div class="input-group-append">
      <button class="btn btn-primary" (click)="saveItem()"> Save </button>
      <button class="btn btn-default" (click)="cancelEditing()"> Cancel </button>
      <button class="btn btn-danger" (click)="deleteItem()"> Delete </button>
  </div>
</div>

// Lecture_10/vue-app/src/components/activeItem.vue
<template>
  <div class="input-group col-md-8">
    <span class="input-group-addon">
         {{index}}.
    </span>
    <input class="form-control" type="text" v-model="inputValue"/>
    <span class="input-group-append">
      <button class="btn btn-primary"  v-on:click="saveItem"> Save </button>
      <button class="btn btn-default"  v-on:click="cancelEditing"> Cancel </button>
      <button class="btn btn-danger"  v-on:click="deleteItem"> Delete </button>
    </span>
  </div>
</template>

<script>
import Vue from 'vue'
import { Component } from 'vue-property-decorator'

export default Component({props: [
  'item',
  'index'
]})(
  class activeItem extends Vue {
    inputValue = this.item.text;

    saveItem () {
      this.$emit('onSaveItem', this.inputValue)
    }

    cancelEditing () {
      this.$emit('onCancelEditing')
    }

    deleteItem () {
      this.$emit('onDeleteItem')
    }
  }
)
</script>
