// Lecture_10/vue-app/src/components/list.vue
<template>
  <div class="mx-auto mt-5 col-md-8">
    <ul class="list-group" id="list">
      <add-item @onAddNewItem="addNewItem" />
      <li v-for="(item, index) in items" :key="item.id" class="list-group-item">
        <listItem
          :index="index + 1"
          :item="item"
          @onSaveItem="editItem"
          @onDeleteItem="deleteItem"
          @onToggleItem="toggleItem"
        />
      </li>
    </ul>
  </div>
</template>

<script>

import Vue from 'vue'
import { Component } from 'vue-property-decorator'
import addItem from './addItem'
import activeItem from './activeItem'
import inactiveItem from './inactiveItem'
import {getDefaultList} from '../utils/getDefaultList'
import {guid} from '../utils/guid'
import listItem from './listItem'

// export default Component({})(
//  class List extends Vue {
@Component({
  components: { listItem, addItem, activeItem, inactiveItem }
})
export default class list extends Vue {
  items = getDefaultList();

  addNewItem (text) {
    const item = {
      id: guid(),
      text,
      isActive: false
    }

    this.items.push(item)
  }

  editItem (id, text) {
    this.items = this.items.map(item => (item.id === id
      ? { ...item, text, isActive: !item.isActive }
      : item
    ))
  }

  toggleItem (id) {
    this.items = this.items.map(item => (item.id === id
      ? { ...item, isActive: !item.isActive }
      : item
    ))
  }

  deleteItem (id) {
    this.items = this.items.filter(item => (item.id !== id))
  }
}
</script>

// Lecture_10/angular-app/src/app/list/list.component/list.component.ts
import {Component} from '@angular/core';
import {ListItem} from '../../../models/ListItem';
import {guid} from '../../../utils/guid';
import {DefaultListService} from '../../../services/DefaultListService';

@Component({
  selector: 'app-list',
  templateUrl: './list.component.html',
  styleUrls: []
})

export class ListComponent {
  items: ListItem[];
  constructor(private  listService: DefaultListService) {
    this.items = this.listService.getDefaultList();
  }

  addNewItem(text: string) {
    const item: ListItem = {
      id: guid(),
      text,
      isActive: false
    };

    this.items.push(item);
  }

  toggleItem(id: Uuid) {
    this.items = this.items.map(item => (item.id === id
        ? { ...item, isActive: !item.isActive }
        : item
    ));
  }

  editItem(id: Uuid, text: string) {
    this.items = this.items.map(item => (item.id === id
        ? { ...item, text, isActive: !item.isActive }
        : item
    ));
  }

  deleteItem(id: Uuid) {
    this.items = this.items.filter(item => (item.id !== id))
  }
}

<div class="mx-auto mt-5 col-md-8">
  <ul class="list-group">
    <app-add-item (onAddItem)="addNewItem($event)"></app-add-item>
    <li *ngFor="let item of items; let i = index" [attr.data-index]="i"  class="list-group-item">
      <div>
        <app-active-item *ngIf="item.isActive" [index]="i" [item]="item" (onSaveItem)="editItem(item.id, $event)"
                    (onDeleteItem)="deleteItem(item.id)" (onCancelEditing)="toggleItem(item.id)"></app-active-item>
        <app-inactive-item *ngIf="!item.isActive" [index]="i" [item]="item" (click)="toggleItem(item.id)"></app-inactive-item>
      </div>
    </li>
  </ul>
</div>
